languageCode = "en"
languageName = ""
weight = 1
title = "welcome to my crib"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"

[params.author]
  name = "murfalo"
  email = "howdy@murfalo.com"
  image = "img/murfalo.png"
  headline = "check out my cool stuff"
  bio = "check out my cool stuff"
  links = [
    { email = "mailto:howdy@murfalo.com" },
    { github = "https://github.com/murfalo" },
    { google-scholar = "https://scholar.google.com/citations?user=zC_z7igAAAAJ" },
    { linkedin = "https://www.linkedin.com/in/murfalo" },
    { twitter = "https://twitter.com/mvrfalo" },
    { bluesky = "https://bsky.app/profile/murfalo.bsky.social" },
    { instagram = "https://instagram.com/mvrfalo" },
  ]
